COT-04: Criar controller e serviço para alterar cotinha
EduardoHenrique18/cotinha pull request #3
Opened 2021-07-31 05:47 UTC by Gugastorme

2021-07-31 05:53 UTC, EduardoHenrique18 commented on src/main/java/com/cotinha/cotinha/controlers/CotaControler.java
> +    public ResponseEntity<Void> emailSave(@RequestBody Cota cota){
alterar o nome do metodo email save para save

2021-07-31 06:17 UTC, EduardoHenrique18 commented on src/main/java/com/cotinha/cotinha/repository/Userrepository.java
> +public interface Userrepository extends JpaRepository<User, Long>{
alterar nome da classe para o padrão camel case

2021-07-31 06:23 UTC, EduardoHenrique18 requested changes

2021-07-31 06:23 UTC, EduardoHenrique18 commented on src/main/java/com/cotinha/cotinha/services/UserService.java
> +        User user1 = userrepository.findByEmail(user.getEmail());
alterar o else e refinar o nome das variaveis

2021-07-31 20:55 UTC, EduardoHenrique18 commented on src/main/java/com/cotinha/cotinha/exceptions/CotaNotFound.java
> +    public CotaNotFound(String message){
deixar o comentario estatico, não passar no parametro

2021-07-31 20:56 UTC, EduardoHenrique18 commented on src/main/java/com/cotinha/cotinha/services/CotaService.java
> +        Optional<Cota> cota = cotaRepository.findById(id);
alterar aqui tambem o erro cotaNotFound para não passar mensagem

2021-07-31 21:02 UTC, EduardoHenrique18 commented on src/main/java/com/cotinha/cotinha/controlers/CotaControler.java
> +    public ResponseEntity<?> find(@PathVariable Long id) throws CotaNotFound {
tratar os erros numa classe de handle para devolver uma mensagem tratada

2021-07-31 21:06 UTC, EduardoHenrique18 commented on src/main/java/com/cotinha/cotinha/services/CotaService.java
> +        return cota.orElseThrow(() -> new CotaNotFound("Id não encontrado"));
tratar metodo orElsseThrow, não esta entrando nesa condição, pois a cota pode vir empty() e não null

2021-07-31 21:07 UTC, EduardoHenrique18 commented on src/main/java/com/cotinha/cotinha/services/CotaService.java
> +    public Cota cotaFind(Long id) throws CotaNotFound {
tratar parametro em caso de ser nullo

2021-07-31 21:08 UTC, EduardoHenrique18 commented on src/main/java/com/cotinha/cotinha/services/CotaService.java
> +        cotaFind(id);
cotaFind no delete não é boa opção, testar o delete sozinho sem precisar buscar antes

2021-07-31 21:12 UTC, EduardoHenrique18 commented on src/main/java/com/cotinha/cotinha/services/CotaService.java
> +        cotaFind(cota.getId());
tratar esse ponto do cotaFind, testar se é necessario

2021-08-02 20:59 UTC, Gugastorme commented on src/main/java/com/cotinha/cotinha/services/CotaService.java
> +        cotaFind(cota.getId());
Fiz alguns testes agora pouco e sem o Find, o Patch se comporta como um Post, assim criando e não dando patch em algo já existente.

2021-08-02 21:08 UTC, Gugastorme commented on src/main/java/com/cotinha/cotinha/services/CotaService.java
> +        cotaFind(id);
Funciona Ok, não vem a exception personalizada e sim o erro que o próprio spring nós da "No class com.cotinha.cotinha.models.Cota entity with id 2 exists!" O que é basicamente a mesma coisa. No postman: 500

2021-08-02 21:10 UTC, Gugastorme commented on src/main/java/com/cotinha/cotinha/services/CotaService.java
> +    public Cota cotaFind(Long id) throws CotaNotFound {
orElse throw tratando no caso de nulo.

2021-08-02 21:46 UTC, Gugastorme commented on src/main/java/com/cotinha/cotinha/exceptions/CotaNotFound.java
> +    public CotaNotFound(String message){
Done

2021-08-02 21:47 UTC, Gugastorme commented on src/main/java/com/cotinha/cotinha/services/UserService.java
> +        User user1 = userrepository.findByEmail(user.getEmail());
Alterado, refinado.

2021-08-02 21:55 UTC, Gugastorme commented on src/main/java/com/cotinha/cotinha/repository/Userrepository.java
> +public interface Userrepository extends JpaRepository<User, Long>{
Done

2021-08-02 21:56 UTC, Gugastorme commented on src/main/java/com/cotinha/cotinha/controlers/CotaControler.java
> +    public ResponseEntity<Void> emailSave(@RequestBody Cota cota){
Done.

2021-08-03 01:19 UTC, Gugastorme commented on src/main/java/com/cotinha/cotinha/controlers/CotaControler.java
> +    public ResponseEntity<?> find(@PathVariable Long id) throws CotaNotFound {
Done.

2021-08-03 01:19 UTC, Gugastorme commented on src/main/java/com/cotinha/cotinha/services/CotaService.java
> +        Optional<Cota> cota = cotaRepository.findById(id);
Done

2021-08-03 01:29 UTC, Gugastorme commented on src/main/java/com/cotinha/cotinha/services/CotaService.java
> +        cotaFind(id);
Volta como 500 internal server error, porém se eu passar o find primeiro, ele vem com o erro personalizado 400 - NOT_FOUND ( inclusive no postman)

2021-08-06 00:00 UTC, EduardoHenrique18 approved these changes

2021-08-06 00:01 UTC, EduardoHenrique18 approved these changes

2021-08-06 00:01 UTC, EduardoHenrique18 approved these changes
Aprovado

2021-08-06 00:02 UTC, merged